import logo from '../images/logo.jpg';
import Dentist2 from '../images/Dentist2.jpg';
import teeth from '../images/teeth.webp';
import sara from '../images/sara.jpg';
import img1 from '../images/img1.jpg';
import img2 from '../images/img2.jpg';
import img3 from '../images/img3.jpg';
import img4 from '../images/img4.jpg';
import img5 from '../images/img5.jpg';
import img6 from '../images/img6.jpg';
import tooth from '../images/tooth.png';
import tooth3 from '../images/tooth3.jpg';
import tooth5 from '../images/tooth5.png'
import teeth5 from '../images/teeth5.jpg'
export { logo,Dentist2,teeth,sara,img1,img2,img3,img4,img5,img6,tooth,tooth3,tooth5 ,teeth5};